### ISSUE TITLE
No

### ISSUE THREAD

**Issue by Bwc9876** [KusamiWomba/YeeBot#1]
Getting an error when trying to run it in Minecraft forge

`Error: Haha stupid head`

**Comment by KusamiWomba** [comment]
Sorry thats because i hate you on a personal level.

**Comment by Bwc9876** [comment]
Hate to necropost this but I need a fix or else my mom is going to kill me

`Today is gonna be the day
That they're gonna throw it back to you
By now you should've somehow
Realized what you gotta do
I don't believe that anybody
Feels the way I do, about you now
Backbeat, the word was on the street
That the fire in your heart is out
I'm sure you've heard it all before
But you never really had a doubt
I don't believe that anybody
Feels the way I do about you now
And all the roads we have to walk are winding
And all the lights that lead us there are blinding
There are many things that I
Would like to say to you but I don't know how
Because maybe, you're gonna be the one that saves me
And after all, you're my wonderwall
Today was gonna be the day
But they'll never throw it back to you
By now you should've somehow
Realized what you're not to…`

**Comment by KusamiWomba** [comment]
> 
> 
> Hate to necropost this but I need a fix or else my mom is going to kill me
> 
> `Today is gonna be the day That they're gonna throw it back to you By now you should've somehow Realized what you gotta do I don't believe that anybody Feels the way I do, about you now Backbeat, the word was on the street That the fire in your heart is out I'm sure you've heard it all before But you never really had a doubt I don't believe that anybody Feels the way I do about you now And all the roads we have to walk are winding And all the lights that lead us there are blinding There are many things that I Would like to say to you but I don't know how Because maybe, you're gonna be the one that saves me And after all, you're my wonderwall Today was gonna be the day But they'll never throw it back to you By now you should've somehow Realized what you're not to…`

doo doo
